services:
  mcp-server-mock:
    image: mcp-server-mock
    container_name: mcp-server-mock
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MCP_TOOLS_SPEC_LOCATION_PATTERN: "./tools/*.yml"
    ports:
      - "${HOST_PORT:-11969}:${SERVER_PORT:-8080}"
    restart: unless-stopped
