serverPort: 8080
toolsSpecLocationPattern: ./tools/*.yml
viewportsDir: ./viewports
viewportRefreshIntervalMs: 30000
httpMaxBodyBytes: 1048576
observability:
  logEnabled: true
  logMaxBodyLength: 2000
  logIncludeHeaders: false
